@startuml
title <size:24>Component View: Webshop - Webshop WebServer</size>\n<size:24>Webshop - Components</size>

set separator none
top to bottom direction
skinparam ranksep 60
skinparam nodesep 30
hide stereotype

<style>
  root {
    BackgroundColor: #ffffff;
    FontColor: #444444;
  }
  // Element,Component
  .Element-RWxlbWVudCxDb21wb25lbnQ= {
    BackgroundColor: #85bbf0;
    LineColor: #5d82a8;
    LineStyle: 0;
    LineThickness: 2;
    FontColor: #000000;
    FontSize: 24;
    HorizontalAlignment: center;
    Shadowing: 0;
    MaximumWidth: 450;
  }
  // Element,Component,Repository
  .Element-RWxlbWVudCxDb21wb25lbnQsUmVwb3NpdG9yeQ== {
    BackgroundColor: #999999;
    LineColor: #6b6b6b;
    LineStyle: 0;
    LineThickness: 2;
    FontColor: #000000;
    FontSize: 24;
    HorizontalAlignment: center;
    Shadowing: 0;
    MaximumWidth: 450;
  }
  // Element,Container,Database
  .Element-RWxlbWVudCxDb250YWluZXIsRGF0YWJhc2U= {
    BackgroundColor: #999999;
    LineColor: #6b6b6b;
    LineStyle: 0;
    LineThickness: 2;
    FontColor: #ffffff;
    FontSize: 24;
    HorizontalAlignment: center;
    Shadowing: 0;
    MaximumWidth: 450;
  }
  // Element,Software System
  .Element-RWxlbWVudCxTb2Z0d2FyZSBTeXN0ZW0= {
    BackgroundColor: #1168bd;
    LineColor: #0b4884;
    LineStyle: 0;
    LineThickness: 2;
    FontColor: #ffffff;
    FontSize: 24;
    HorizontalAlignment: center;
    Shadowing: 0;
    MaximumWidth: 450;
  }
  // Element,Software System,Infrastructure,Security
  .Element-RWxlbWVudCxTb2Z0d2FyZSBTeXN0ZW0sSW5mcmFzdHJ1Y3R1cmUsU2VjdXJpdHk= {
    BackgroundColor: #333333;
    LineColor: #232323;
    LineStyle: 0;
    LineThickness: 2;
    FontColor: #ffffff;
    FontSize: 24;
    HorizontalAlignment: center;
    Shadowing: 0;
    MaximumWidth: 450;
  }
  // Relationship
  .Relationship-UmVsYXRpb25zaGlw {
    LineThickness: 2;
    LineStyle: 10-10;
    LineColor: #444444;
    FontColor: #444444;
    FontSize: 24;
  }
  // Webshop
  .Boundary-V2Vic2hvcA== {
    BackgroundColor: #ffffff;
    LineColor: #0b4884;
    LineStyle: 0;
    LineThickness: 2;
    FontColor: #ffffff;
    FontSize: 24;
    HorizontalAlignment: center;
    Shadowing: 0;
  }
  // Webshop WebServer
  .Boundary-V2Vic2hvcCBXZWJTZXJ2ZXI= {
    BackgroundColor: #ffffff;
    LineColor: #2e6295;
    LineStyle: 0;
    LineThickness: 2;
    FontColor: #ffffff;
    FontSize: 24;
    HorizontalAlignment: center;
    Shadowing: 0;
  }
</style>

rectangle "==Product Management System\n<size:16>[Software System]</size>\n\nThe Product Management System" <<Element-RWxlbWVudCxTb2Z0d2FyZSBTeXN0ZW0=>> as ProductManagementSystem
rectangle "==Warehouse Service\n<size:16>[Software System]</size>\n\nThe warehouse inventory system." <<Element-RWxlbWVudCxTb2Z0d2FyZSBTeXN0ZW0=>> as WarehouseService
rectangle "==Order Service\n<size:16>[Software System]</size>\n\nThe order management system." <<Element-RWxlbWVudCxTb2Z0d2FyZSBTeXN0ZW0=>> as OrderService
hexagon "==Keycloak IAM\n<size:16>[Software System]</size>\n\nIdentity and Access Management." <<Element-RWxlbWVudCxTb2Z0d2FyZSBTeXN0ZW0sSW5mcmFzdHJ1Y3R1cmUsU2VjdXJpdHk=>> as KeycloakIAM

rectangle "Webshop\n<size:16>[Software System]</size>" <<Boundary-V2Vic2hvcA==>> {
  rectangle "Webshop WebServer\n<size:16>[Container]</size>" <<Boundary-V2Vic2hvcCBXZWJTZXJ2ZXI=>> {
    rectangle "==ProductController\n<size:16>[Component]</size>\n\nHandles product listing." <<Element-RWxlbWVudCxDb21wb25lbnQ=>> as Webshop.WebshopWebServer.ProductController
    rectangle "==ShoppingCartController\n<size:16>[Component]</size>\n\nHandles cart view." <<Element-RWxlbWVudCxDb21wb25lbnQ=>> as Webshop.WebshopWebServer.ShoppingCartController
    rectangle "==OrderHistoryController\n<size:16>[Component]</size>\n\nHandles customer order history." <<Element-RWxlbWVudCxDb21wb25lbnQ=>> as Webshop.WebshopWebServer.OrderHistoryController
    rectangle "==ProductSyncController\n<size:16>[Component]</size>\n\nHandles product synchronization API." <<Element-RWxlbWVudCxDb21wb25lbnQ=>> as Webshop.WebshopWebServer.ProductSyncController
    rectangle "==StockSyncController\n<size:16>[Component]</size>\n\nHandles stock synchronization API." <<Element-RWxlbWVudCxDb21wb25lbnQ=>> as Webshop.WebshopWebServer.StockSyncController
    rectangle "==ProductRepository\n<size:16>[Component]</size>\n\nHandles data access for products." <<Element-RWxlbWVudCxDb21wb25lbnQsUmVwb3NpdG9yeQ==>> as Webshop.WebshopWebServer.ProductRepository
  }

  database "==Webshop Database\n<size:16>[Container]</size>\n\nThe database." <<Element-RWxlbWVudCxDb250YWluZXIsRGF0YWJhc2U=>> as Webshop.WebshopDatabase
}

ProductManagementSystem --> KeycloakIAM <<Relationship-UmVsYXRpb25zaGlw>> : "Verifies tokens with"
WarehouseService --> KeycloakIAM <<Relationship-UmVsYXRpb25zaGlw>> : "Verifies tokens with"
OrderService --> KeycloakIAM <<Relationship-UmVsYXRpb25zaGlw>> : "Verifies tokens with"
KeycloakIAM --> ProductManagementSystem <<Relationship-UmVsYXRpb25zaGlw>> : "Returns token to"
Webshop.WebshopWebServer.OrderHistoryController --> KeycloakIAM <<Relationship-UmVsYXRpb25zaGlw>> : "Requests token from"
Webshop.WebshopWebServer.ProductController --> Webshop.WebshopWebServer.ProductRepository <<Relationship-UmVsYXRpb25zaGlw>> : "Uses"
Webshop.WebshopWebServer.ShoppingCartController --> Webshop.WebshopWebServer.ProductRepository <<Relationship-UmVsYXRpb25zaGlw>> : "Uses"
Webshop.WebshopWebServer.OrderHistoryController --> OrderService <<Relationship-UmVsYXRpb25zaGlw>> : "Fetches orders from"
Webshop.WebshopWebServer.ProductSyncController --> Webshop.WebshopWebServer.ProductRepository <<Relationship-UmVsYXRpb25zaGlw>> : "Uses"
Webshop.WebshopWebServer.StockSyncController --> Webshop.WebshopWebServer.ProductRepository <<Relationship-UmVsYXRpb25zaGlw>> : "Uses"
Webshop.WebshopWebServer.ProductRepository --> Webshop.WebshopDatabase <<Relationship-UmVsYXRpb25zaGlw>> : "Reads from and writes to"
ProductManagementSystem --> Webshop.WebshopWebServer.ProductSyncController <<Relationship-UmVsYXRpb25zaGlw>> : "Sends updates to"
WarehouseService --> Webshop.WebshopWebServer.StockSyncController <<Relationship-UmVsYXRpb25zaGlw>> : "Sends stock updates to"
ProductManagementSystem --> WarehouseService <<Relationship-UmVsYXRpb25zaGlw>> : "Sends product updates to"
OrderService --> WarehouseService <<Relationship-UmVsYXRpb25zaGlw>> : "Reserves stock in"
OrderService --> WarehouseService <<Relationship-UmVsYXRpb25zaGlw>> : "Notifies of confirmed order"

@enduml