apiVersion: policy/v1
kind: RequirementSet
metadata:
  name: runtime-product-management-delete
  version: "1.0"
spec:
  requirements:
    - id: REQ-018
      type: runtime
      c4_level: component
      description: "The ProductController shall allow a productManager to delete a product entry at /products/delete."
      priority: critical
      tracesTo: "REQ-014"
      runtime_validation:
        url: "http://localhost:8001/products/delete"
        expected_status: 200