apiVersion: policy/v1
kind: RequirementSet
metadata:
  name: warehouse-add-individual
  version: "1.0"
spec:
  requirements:
    - id: REQ-038
      type: functional
      c4_level: component
      description: "The Warehouse Service shall allow adding Product Individuals (with serial number and state) to a Delivery."
      priority: high
      tracesTo: "REQ-036"
      functional_validation:
        test_file: "e2e-tests/cypress/e2e/warehouse_delivery.cy.js"