apiVersion: policy/v1
kind: RequirementSet
metadata:
  name: invoice-payment
  version: "1.0"
spec:
  requirements:
    - id: REQ-066
      type: functional
      c4_level: component
      description: "The Order Service shall allow Order Managers to mark an Invoice as paid."
      priority: high
      tracesTo: "REQ-065"
      validation_policy: "policies/check_code_structure.rego"
      code_validation:
        file_path: "applications/orderService/src/main/java/com/example/order/InvoiceController.java"
        method_name: "markPaid"
      model_validation:
        source: "Order Manager"
        destination: "Order WebServer"
        description_contains: "marks invoice as paid"
