apiVersion: policy/v1
kind: RequirementSet
metadata:
  name: functional-stock-reservation
  version: "1.0"
spec:
  requirements:
    - id: REQ-053
      type: functional
      c4_level: component
      description: "The Order Service shall reserve stock in the Warehouse Service when an order is placed."
      priority: high
      tracesTo: "REQ-052"
      validation_policy: "policies/check_dependency.rego"
      code_validation:
        file_path: "orderService/src/main/java/com/example/order/StockReservationService.java"
        imports:
          - "java.net.http.HttpClient"