apiVersion: policy/v1
kind: RequirementSet
metadata:
  name: pm-sync-integration
  version: "1.0"
spec:
  requirements:
    - id: REQ-025
      type: functional
      c4_level: component
      description: "The Product Management System shall provide a mechanism to manually synchronize product updates to the Webshop API."
      priority: high
      tracesTo: 
        - "REQ-010"
        - "REQ-059"
      # Validated by code check, functional test, AND pact contract
      validation_policy: "policies/check_dependency.rego"
      code_validation:
        file_path: "applications/productManagementSystem/src/main/java/com/example/productmanagement/ProductService.java"
        imports:
          - "java.net.http.HttpClient"
      functional_validation:
        test_file: "e2e-tests/cypress/e2e/product_sync.cy.js"
      pact_validation:
        consumer: "ProductManagementSystem"
        provider: "WebshopService"
