apiVersion: policy/v1
kind: RequirementSet
metadata:
  name: contract-product-sync
  version: "1.0"
spec:
  requirements:
    - id: REQ-088
      type: functional
      c4_level: component
      description: "The Product Sync payload shall include id, name, description, price, unit, and type."
      priority: high
      tracesTo: "REQ-024"
      validation_policy: "policies/check_code_structure.rego"
      code_validation:
        file_path: "applications/webshop/src/main/java/com/example/webshop/ProductSyncController.java"
        contains: "price"
