apiVersion: policy/v1
kind: RequirementSet
metadata:
  name: pm-warehouse-sync
  version: "1.0"
spec:
  requirements:
    - id: REQ-033
      type: functional
      c4_level: component
      description: "The Product Management System shall send product updates to the Warehouse Service when a product is created or updated."
      priority: high
      tracesTo: "REQ-010"
      # Validated by code check AND functional test
      validation_policy: "policies/check_dependency.rego"
      code_validation:
        file_path: "productManagementSystem/src/main/java/com/example/productmanagement/ProductService.java"
        imports:
          - "java.net.http.HttpClient"
      functional_validation:
        test_file: "e2e-tests/cypress/e2e/warehouse_sync.cy.js"