apiVersion: policy/v1
kind: RequirementSet
metadata:
  name: container-loki
  version: "1.0"
spec:
  requirements:
    - id: REQ-056
      type: architectural
      c4_level: container
      description: "Loki shall be used for log aggregation."
      priority: high
      tracesTo: "REQ-055"
      validation_policy: "policies/check_containers.rego"
      model_validation:
        parent: "Observability System"
        container: "Loki"