apiVersion: policy/v1
kind: RequirementSet
metadata:
  name: variant-generation
  version: "1.0"
spec:
  requirements:
    - id: REQ-071
      type: functional
      c4_level: component
      description: "The Product Management System shall generate product variants based on attributes."
      priority: high
      tracesTo: "REQ-012"
      validation_policy: "policies/check_code_structure.rego"
      code_validation:
        file_path: "applications/productManagementSystem/src/main/java/com/example/productmanagement/ProductService.java"
        contains: "generateVariants"
