apiVersion: policy/v1
kind: RequirementSet
metadata:
  name: loyalty-point-accumulation
  version: "1.0"
spec:
  requirements:
    - id: REQ-092
      type: functional
      c4_level: component
      description: "The Loyalty Service shall accrue points for a customer when an order is confirmed."
      priority: high
      tracesTo: "REQ-091"
      validation_policy: "policies/check_code_structure.rego"
      code_validation:
        file_path: "applications/loyaltyService/src/main/java/com/example/loyalty/PointService.java"
        contains: "accruePoints"
